### ISSUE TITLE
Unrocognized  Arguments

### ISSUE THREAD

**Issue by ccfman2004** [lamusmaser/ta_fix_for_video_redirection#1]
When I try to run:

`python ta_fix_for_redirection.py -Y -B -r`

As instructed by the readme to do the dry run I get the following error:

`ta_fix_for_redirection.py: error: unrecognized arguments: -r`

`usage: ta_fix_for_redirection.py [-h] [-d SOURCE_DIR] [-Y] [-s YTDLP_SLEEP] [-D] [-B]`

**Comment by lamusmaser** [comment]
That is because it is incorrectly documented holdover from another script. The `DRY_RUN` argument comes through with `-D`.

I will update the README.

**Comment by ccfman2004** [comment]
Thank you.
